import React, { useEffect, useRef } from 'react';
import { useLabStoreEnergy } from '../../store/energyStore';

export const VisualizationCanvasEnergy: React.FC = () => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const { position, speed, initialHeight, angle, mass, gravity, friction, isRunning, hasFinished } = useLabStoreEnergy();
  useEffect(() => { const canvas = canvasRef.current; const context = canvas?.getContext('2d'); if (!canvas || !context) return; const width = canvas.width; const height = canvas.height; context.clearRect(0, 0, width, height); context.fillStyle = '#ecfeff'; context.fillRect(0, 0, width, height); const baseX = 100; const baseY = 350; const length = initialHeight / Math.max(Math.sin(angle * Math.PI / 180), 0.1); const scale = 500 / Math.max(length, 1); const endX = baseX + length * Math.cos(angle * Math.PI / 180) * scale; const endY = baseY - length * Math.sin(angle * Math.PI / 180) * scale; context.strokeStyle = '#475569'; context.lineWidth = 16; context.beginPath(); context.moveTo(baseX, baseY); context.lineTo(endX, endY); context.stroke(); const ballX = baseX + Math.min(position, length) * Math.cos(angle * Math.PI / 180) * scale; const ballY = baseY - Math.min(position, length) * Math.sin(angle * Math.PI / 180) * scale; context.fillStyle = '#0891b2'; context.beginPath(); context.arc(ballX, ballY - 15, 18, 0, Math.PI * 2); context.fill(); context.fillStyle = '#164e63'; context.font = 'bold 13px monospace'; context.textAlign = 'center'; context.fillText(`${mass.toFixed(2)} kg`, ballX, ballY - 10); context.fillStyle = '#0e7490'; context.fillRect(18, 18, 245, 78); context.fillStyle = '#cffafe'; context.textAlign = 'left'; context.font = '12px monospace'; context.fillText(`h = ${initialHeight.toFixed(2)} m`, 30, 42); context.fillText(`v = ${speed.toFixed(2)} m/s`, 30, 62); context.fillText(`f = ${friction.toFixed(2)}`, 30, 82); context.fillStyle = hasFinished ? '#166534' : isRunning ? '#92400e' : '#475569'; context.textAlign = 'right'; context.fillText(hasFinished ? 'FINALIZADO' : isRunning ? 'DESLIZANDO' : 'LISTO', width - 20, 32); context.fillStyle = '#334155'; context.textAlign = 'center'; context.fillText(`Energía mecánica y fricción • θ = ${angle}° • g = ${gravity.toFixed(2)} m/s²`, width / 2, height - 15); }, [position, speed, initialHeight, angle, mass, gravity, friction, isRunning, hasFinished]);
  return <canvas ref={canvasRef} width={800} height={400} className="w-full rounded-xl border border-cyan-200 bg-white shadow-lg" style={{ maxWidth: '800px' }} />;
};
