import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, BarChart3, Beaker, BookOpen, FileText, FlaskConical, Home, Menu, Pause, Play, Plus, RotateCcw, Trash2, X } from 'lucide-react';
import { VisualizationCanvasEnergy } from '../components/energy/VisualizationCanvasEnergy';
import { SaveExperimentButton } from '../components/history/SaveExperimentButton';
import { useLabStoreEnergy } from '../store/energyStore';
import { analyzeEnergyData } from '../utils/energyCalculations';
import type { PedagogicalPhaseEnergy } from '../types/energy.types';

const phases: { key: PedagogicalPhaseEnergy; label: string; icon: React.ReactNode; description: string }[] = [
  { key: 'exploration', label: 'Exploración', icon: <FlaskConical size={16} />, description: 'Observa la transformación de energía' },
  { key: 'hypothesis', label: 'Hipótesis', icon: <BookOpen size={16} />, description: 'Predice el efecto de la fricción' },
  { key: 'experimentation', label: 'Experimentación', icon: <Beaker size={16} />, description: 'Compara varias alturas y fricciones' },
  { key: 'analysis', label: 'Análisis', icon: <BarChart3 size={16} />, description: 'Calcula pérdidas y errores' },
  { key: 'conclusion', label: 'Conclusiones', icon: <FileText size={16} />, description: 'Interpreta el balance energético' },
];

export const EnergyPractice: React.FC = () => {
  const state = useLabStoreEnergy();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [hypothesis, setHypothesis] = useState('');
  const [conclusions, setConclusions] = useState('');
  const animationRef = useRef<number | null>(null);
  const lastTimeRef = useRef(0);
  const analysis = analyzeEnergyData(state.dataPoints, state.gravity);
  const currentPhaseIndex = phases.findIndex(item => item.key === state.phase);

  useEffect(() => { const animate = (timestamp: number) => { if (!lastTimeRef.current) lastTimeRef.current = timestamp; const dt = Math.min((timestamp - lastTimeRef.current) / 1000, 0.05); lastTimeRef.current = timestamp; if (dt > 0) state.updateMotion(dt); animationRef.current = requestAnimationFrame(animate); }; if (state.isRunning) { lastTimeRef.current = 0; animationRef.current = requestAnimationFrame(animate); } return () => { if (animationRef.current) cancelAnimationFrame(animationRef.current); }; }, [state.isRunning, state.updateMotion]);

  const controls = <div className="rounded-xl border border-gray-100 bg-white p-5 shadow-md"><h3 className="mb-4 text-lg font-bold text-gray-800">🎛️ Panel de Control</h3><div className="grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-gray-700">Masa: {state.mass.toFixed(2)} kg<input type="range" min="0.1" max="2" step="0.1" value={state.mass} onChange={event => state.setMass(Number(event.target.value))} className="w-full accent-cyan-600" /></label><label className="text-sm font-medium text-gray-700">Altura: {state.initialHeight.toFixed(2)} m<input type="range" min="0.5" max="5" step="0.25" value={state.initialHeight} onChange={event => state.setInitialHeight(Number(event.target.value))} className="w-full accent-cyan-600" /></label><label className="text-sm font-medium text-gray-700">Ángulo: {state.angle}°<input type="range" min="10" max="60" step="1" value={state.angle} onChange={event => state.setAngle(Number(event.target.value))} className="w-full accent-cyan-600" /></label><label className="text-sm font-medium text-gray-700">Fricción: {state.friction.toFixed(2)}<input type="range" min="0" max="0.8" step="0.05" value={state.friction} onChange={event => state.setFriction(Number(event.target.value))} className="w-full accent-cyan-600" /></label></div><div className="mt-4 flex gap-2"><button onClick={state.toggleRunning} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-cyan-600 px-4 py-2 font-medium text-white hover:bg-cyan-700">{state.isRunning ? <><Pause size={18} />Pausar</> : <><Play size={18} />Soltar bloque</>}</button><button onClick={state.reset} className="rounded-lg bg-red-50 px-4 py-2 text-red-700" title="Reiniciar"><RotateCcw size={18} /></button></div></div>;

  return <div className="min-h-screen bg-gradient-to-br from-slate-50 via-cyan-50 to-blue-100"><header className="sticky top-0 z-40 border-b border-cyan-100 bg-white/80 shadow-sm backdrop-blur-md"><div className="container mx-auto flex items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><Link to="/" className="rounded-lg p-2 hover:bg-gray-100"><ArrowLeft size={20} /></Link><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-cyan-600 to-blue-600 text-xl shadow-lg">⚡</div><div><h1 className="text-lg font-bold text-gray-800">Práctica 8: Energía Mecánica</h1><p className="text-xs text-gray-500">Conservación de la energía y fricción</p></div></div><Link to="/" className="hidden items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium md:flex"><Home size={16} />Inicio</Link><button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="rounded-lg p-2 md:hidden">{mobileMenuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header><nav className="border-b border-gray-200 bg-white/60"><div className="container mx-auto px-4"><div className="hidden gap-1 overflow-x-auto py-2 md:flex">{phases.map((item, index) => <button key={item.key} onClick={() => state.setPhase(item.key)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-4 py-2 text-sm font-medium ${state.phase === item.key ? 'bg-cyan-600 text-white' : index <= currentPhaseIndex ? 'text-cyan-700 hover:bg-cyan-50' : 'text-gray-400'}`}>{item.icon}{item.label}</button>)}</div>{mobileMenuOpen && <div className="space-y-1 py-2 md:hidden">{phases.map(item => <button key={item.key} onClick={() => { state.setPhase(item.key); setMobileMenuOpen(false); }} className={`flex w-full items-center gap-2 rounded-lg px-4 py-3 text-left text-sm ${state.phase === item.key ? 'bg-cyan-600 text-white' : 'text-gray-600'}`}>{item.icon}{item.label}</button>)}</div>}</div></nav><div className="container mx-auto px-4 py-3"><div className="rounded-lg border border-cyan-200 bg-cyan-50 px-4 py-2 text-sm text-cyan-800"><strong>Fase {currentPhaseIndex + 1}/5 - {phases[currentPhaseIndex].label}:</strong> {phases[currentPhaseIndex].description}</div></div><main className="container mx-auto px-4 pb-12 pt-2">
    {state.phase === 'exploration' && <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><VisualizationCanvasEnergy />{controls}</div><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">📖 Energía Mecánica</h2><p className="mb-3 text-sm text-gray-700">La energía potencial gravitatoria se transforma en energía cinética. La fricción convierte parte de la energía mecánica en calor.</p><div className="rounded-lg border border-cyan-200 bg-cyan-50 p-3 text-center font-mono text-cyan-800">Eₚ = mgh<br />Eₖ = ½mv²<br />Eₘ = Eₚ + Eₖ</div><p className="mt-3 text-sm text-gray-700">Compara la energía inicial con la final y cuantifica la pérdida producida por la fricción.</p></section></div>}
    {state.phase === 'hypothesis' && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">💡 Hipótesis</h2><p className="mb-3 text-sm text-gray-600">Predice cómo cambiará la velocidad final si aumentas la altura o la fricción.</p><textarea value={hypothesis} onChange={event => setHypothesis(event.target.value)} rows={7} placeholder="Ejemplo: al aumentar la fricción, la energía cinética final disminuirá..." className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" /></section><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">🎯 Objetivos</h2><ul className="space-y-2 text-sm text-gray-700">{['Verificar la transformación de energía', 'Comparar sistemas con y sin fricción', 'Medir la velocidad final', 'Calcular energía perdida', 'Analizar el error experimental'].map((item, index) => <li key={item}><span className="mr-2 inline-flex h-5 w-5 items-center justify-center rounded-full bg-cyan-100 text-xs font-bold text-cyan-700">{index + 1}</span>{item}</li>)}</ul></section></div>}
    {state.phase === 'experimentation' && <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><VisualizationCanvasEnergy />{controls}</div><section className="space-y-4"><div className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">🧪 Procedimiento</h2><ol className="list-decimal space-y-2 pl-5 text-sm text-gray-700"><li>Selecciona altura y fricción.</li><li>Libera el bloque.</li><li>Espera a que llegue al final.</li><li>Pulsa Medir.</li><li>Repite con cinco configuraciones.</li></ol></div><div className="rounded-xl bg-white p-5 shadow-md"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">📋 Mediciones</h2><div className="flex gap-2"><button onClick={state.addDataPoint} className="inline-flex items-center gap-1 rounded-lg bg-cyan-600 px-3 py-1.5 text-sm text-white"><Plus size={16} />Medir</button><button onClick={state.clearDataPoints} className="rounded-lg bg-red-50 px-3 py-1.5 text-red-700" title="Limpiar"><Trash2 size={16} /></button></div></div><div className="max-h-60 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50"><th className="p-2 text-left">#</th><th className="p-2 text-left">h (m)</th><th className="p-2 text-left">v (m/s)</th><th className="p-2 text-left">Eₖ (J)</th></tr></thead><tbody>{state.dataPoints.length === 0 ? <tr><td colSpan={4} className="p-5 text-center text-gray-400">Presiona Medir</td></tr> : state.dataPoints.map((point, index) => <tr key={`${point.initialHeight}-${index}`} className="border-t"><td className="p-2">{index + 1}</td><td className="p-2 font-mono">{point.initialHeight.toFixed(2)}</td><td className="p-2 font-mono">{point.finalSpeed.toFixed(2)}</td><td className="p-2 font-mono">{point.kineticEnergy.toFixed(2)}</td></tr>)}</tbody></table></div></div></section></div>}
    {state.phase === 'analysis' && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">🔬 Análisis de Energía</h2>{analysis ? <div className="space-y-3"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-cyan-50 p-3 text-center"><p className="text-xs text-cyan-600">Energía inicial</p><p className="font-mono text-xl font-bold text-cyan-800">{analysis.theoreticalEnergy.toFixed(2)} J</p></div><div className="rounded-lg bg-blue-50 p-3 text-center"><p className="text-xs text-blue-600">Energía final</p><p className="font-mono text-xl font-bold text-blue-800">{analysis.experimentalEnergy.toFixed(2)} J</p></div></div><p className="rounded-lg bg-yellow-50 p-3 text-sm">Pérdida por fricción: <strong>{analysis.energyLostToFriction.toFixed(2)} J</strong></p><p className="rounded-lg bg-gray-50 p-3 font-mono text-sm">Error energético: {analysis.percentError.toFixed(2)}%<br />Error promedio de velocidad: {analysis.averageSpeedError.toFixed(2)}%<br />R² = {analysis.rSquared.toFixed(4)}</p></div> : <p className="py-8 text-center text-gray-500">Necesitas al menos dos mediciones.</p>}</section><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">❓ Preguntas guía</h2><ol className="list-decimal space-y-3 pl-5 text-sm text-gray-700"><li>¿La energía mecánica se conserva sin fricción?</li><li>¿Cómo cambia la velocidad con la altura?</li><li>¿Qué porcentaje de energía se pierde por fricción?</li><li>¿Qué fuentes de error afectan el experimento?</li></ol></section></div>}
    {state.phase === 'conclusion' && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">📝 Conclusiones</h2><textarea value={conclusions} onChange={event => setConclusions(event.target.value)} rows={8} placeholder="Escribe tus conclusiones aquí..." className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" />{hypothesis && <p className="mt-3 rounded-lg bg-cyan-50 p-3 text-sm text-cyan-800"><strong>Hipótesis:</strong> {hypothesis}</p>}</section><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">📊 Resumen</h2><p className="text-sm text-gray-700">Compara la energía inicial y final y explica el efecto de la fricción.</p>{analysis && <div className="mt-4 space-y-2 text-sm"><p>Energía perdida: <strong>{analysis.energyLostToFriction.toFixed(2)} J</strong></p><p>Error promedio: <strong>{analysis.averageSpeedError.toFixed(2)}%</strong></p></div>}</section></div>}
  </main><div className="container mx-auto px-4"><SaveExperimentButton practiceId="energy" title="Experimento de Conservación de Energía" getPayload={() => ({ ...useLabStoreEnergy.getState(), hypothesis, conclusions, analysis, savedAt: new Date().toISOString() })} /></div><footer className="border-t border-gray-200 bg-white/60 py-4 text-center text-xs text-gray-500">Laboratorio Virtual de Física General • Práctica 8: Energía Mecánica</footer></div>;
};

export default EnergyPractice;
