import { PracticeProgress } from '../components/pedagogy/PracticeProgress';
import React, { useEffect, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowLeft, BarChart3, Beaker, BookOpen, FileText, FlaskConical, Home, Menu, Pause, Play, Plus, RotateCcw, Trash2, X } from 'lucide-react';
import { VisualizationCanvasHooke } from '../components/hooke/VisualizationCanvasHooke';
import { SaveExperimentButton } from '../components/history/SaveExperimentButton';
import { useLabStoreHooke } from '../store/hookeStore';
import { analyzeHookeData } from '../utils/hookeCalculations';
import type { PedagogicalPhaseHooke } from '../types/hooke.types';

const phases: { key: PedagogicalPhaseHooke; label: string; icon: React.ReactNode; description: string }[] = [
  { key: 'exploration', label: 'Exploración', icon: <FlaskConical size={16} />, description: 'Observa cómo responde el resorte a una masa' },
  { key: 'hypothesis', label: 'Hipótesis', icon: <BookOpen size={16} />, description: 'Predice la relación entre fuerza y elongación' },
  { key: 'experimentation', label: 'Experimentación', icon: <Beaker size={16} />, description: 'Construye una tabla con varias masas' },
  { key: 'analysis', label: 'Análisis', icon: <BarChart3 size={16} />, description: 'Determina k con una regresión lineal' },
  { key: 'conclusion', label: 'Conclusiones', icon: <FileText size={16} />, description: 'Interpreta resultados y genera tu reporte' },
];

export const HookePractice: React.FC = () => {
  const { mass, springConstant, gravity, setMass, setSpringConstant, setGravity, isRunning, toggleRunning, reset, updateMotion, dataPoints, addDataPoint, clearDataPoints, phase, setPhase } = useLabStoreHooke();
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [hypothesis, setHypothesis] = useState('');
  const [conclusions, setConclusions] = useState('');
  const animationRef = useRef<number | null>(null);
  const lastTimeRef = useRef(0);
  const analysis = analyzeHookeData(dataPoints, springConstant);
  const currentPhaseIndex = phases.findIndex(item => item.key === phase);

  useEffect(() => {
    const animate = (timestamp: number) => {
      if (!lastTimeRef.current) lastTimeRef.current = timestamp;
      const dt = Math.min((timestamp - lastTimeRef.current) / 1000, 0.05);
      lastTimeRef.current = timestamp;
      if (dt > 0) updateMotion(dt);
      animationRef.current = requestAnimationFrame(animate);
    };
    if (isRunning) {
      lastTimeRef.current = 0;
      animationRef.current = requestAnimationFrame(animate);
    }
    return () => { if (animationRef.current) cancelAnimationFrame(animationRef.current); };
  }, [isRunning, updateMotion]);

  const controls = <div className="rounded-xl border border-gray-100 bg-white p-5 shadow-md"><h3 className="mb-4 text-lg font-bold text-gray-800">🎛️ Panel de Control</h3><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium text-gray-700">Masa: {mass.toFixed(2)} kg<input type="range" min="0.05" max="0.8" step="0.05" value={mass} onChange={event => setMass(Number(event.target.value))} className="w-full accent-blue-600" /></label><label className="text-sm font-medium text-gray-700">Constante k: {springConstant.toFixed(1)} N/m<input type="range" min="5" max="30" step="0.5" value={springConstant} onChange={event => setSpringConstant(Number(event.target.value))} className="w-full accent-blue-600" /></label><label className="text-sm font-medium text-gray-700">Gravedad: {gravity.toFixed(2)} m/s²<input type="range" min="1" max="25" step="0.1" value={gravity} onChange={event => setGravity(Number(event.target.value))} className="w-full accent-blue-600" /></label></div><div className="mt-4 flex gap-2"><button onClick={toggleRunning} className="flex flex-1 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2 font-medium text-white hover:bg-blue-700">{isRunning ? <><Pause size={18} />Pausar</> : <><Play size={18} />Soltar masa</>}</button><button onClick={reset} className="rounded-lg bg-red-50 px-4 py-2 text-red-700 hover:bg-red-100" title="Reiniciar"><RotateCcw size={18} /></button></div></div>;

  return <div className="min-h-screen bg-gradient-to-br from-slate-50 via-blue-50 to-cyan-100"><header className="sticky top-0 z-40 border-b border-blue-100 bg-white/80 shadow-sm backdrop-blur-md"><div className="container mx-auto flex items-center justify-between px-4 py-3"><div className="flex items-center gap-3"><Link to="/" className="rounded-lg p-2 hover:bg-gray-100"><ArrowLeft size={20} /></Link><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-gradient-to-br from-blue-600 to-cyan-600 text-xl shadow-lg">🪀</div><div><h1 className="text-lg font-bold text-gray-800">Práctica 7: Ley de Hooke</h1><p className="text-xs text-gray-500">Constante elástica de un resorte</p></div></div><Link to="/" className="hidden items-center gap-2 rounded-lg bg-gray-100 px-4 py-2 text-sm font-medium md:flex"><Home size={16} />Inicio</Link><button onClick={() => setMobileMenuOpen(!mobileMenuOpen)} className="rounded-lg p-2 md:hidden">{mobileMenuOpen ? <X size={20} /> : <Menu size={20} />}</button></div></header><nav className="border-b border-gray-200 bg-white/60"><div className="container mx-auto px-4"><div className="hidden gap-1 overflow-x-auto py-2 md:flex">{phases.map((item, index) => <button key={item.key} onClick={() => setPhase(item.key)} className={`flex items-center gap-2 whitespace-nowrap rounded-lg px-4 py-2 text-sm font-medium ${phase === item.key ? 'bg-blue-600 text-white' : index <= currentPhaseIndex ? 'text-blue-700 hover:bg-blue-50' : 'text-gray-400'}`}>{item.icon}{item.label}</button>)}</div>{mobileMenuOpen && <div className="space-y-1 py-2 md:hidden">{phases.map(item => <button key={item.key} onClick={() => { setPhase(item.key); setMobileMenuOpen(false); }} className={`flex w-full items-center gap-2 rounded-lg px-4 py-3 text-left text-sm ${phase === item.key ? 'bg-blue-600 text-white' : 'text-gray-600'}`}>{item.icon}{item.label}</button>)}</div>}</div></nav><div className="container mx-auto px-4 py-3"><div className="rounded-lg border border-blue-200 bg-blue-50 px-4 py-2 text-sm text-blue-800"><strong>Fase {currentPhaseIndex + 1}/5 - {phases[currentPhaseIndex].label}:</strong> {phases[currentPhaseIndex].description}</div></div><main className="container mx-auto px-4 pb-12 pt-2">
    {phase === 'exploration' && <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><VisualizationCanvasHooke />{controls}</div><div className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">📖 Ley de Hooke</h2><p className="mb-3 text-sm text-gray-700">Dentro del límite elástico, la fuerza aplicada es proporcional a la elongación del resorte.</p><div className="rounded-lg border border-blue-200 bg-blue-50 p-3 text-center font-mono text-blue-800">F = k · x<br />k = F / x</div><p className="mt-3 text-sm text-gray-700">El objetivo es determinar experimentalmente la constante k y comprobar si la relación F-x es lineal.</p></div></div>}
    {phase === 'hypothesis' && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">💡 Planteamiento de Hipótesis</h2><p className="mb-3 text-sm text-gray-600">Predice qué ocurrirá al aumentar la masa y cómo se relacionarán F y x.</p><textarea value={hypothesis} onChange={event => setHypothesis(event.target.value)} rows={7} placeholder="Ejemplo: al duplicar la masa, la fuerza y la elongación aumentarán proporcionalmente..." className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" /></section><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">🎯 Objetivos</h2><ul className="space-y-2 text-sm text-gray-700">{['Relacionar fuerza y elongación', 'Medir al menos cinco configuraciones', 'Obtener k mediante pendiente', 'Evaluar el error experimental', 'Determinar el límite de proporcionalidad'].map((item, index) => <li key={item}><span className="mr-2 inline-flex h-5 w-5 items-center justify-center rounded-full bg-blue-100 text-xs font-bold text-blue-700">{index + 1}</span>{item}</li>)}</ul></section></div>}
    {phase === 'experimentation' && <div className="grid gap-6 lg:grid-cols-3"><div className="space-y-4 lg:col-span-2"><VisualizationCanvasHooke />{controls}</div><section className="space-y-4"><div className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">🧪 Procedimiento</h2><ol className="list-decimal space-y-2 pl-5 text-sm text-gray-700"><li>Selecciona una masa.</li><li>Suéltala y espera el equilibrio.</li><li>Pulsa <strong>Medir</strong>.</li><li>Repite con cinco masas diferentes.</li><li>Compara la pendiente con k.</li></ol></div><div className="rounded-xl bg-white p-5 shadow-md"><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-bold">📋 Mediciones</h2><div className="flex gap-2"><button onClick={addDataPoint} className="inline-flex items-center gap-1 rounded-lg bg-blue-600 px-3 py-1.5 text-sm text-white"><Plus size={16} />Medir</button><button onClick={clearDataPoints} className="rounded-lg bg-red-50 px-3 py-1.5 text-red-700" title="Limpiar"><Trash2 size={16} /></button></div></div><div className="max-h-60 overflow-x-auto"><table className="w-full text-sm"><thead><tr className="bg-gray-50"><th className="p-2 text-left">#</th><th className="p-2 text-left">m (kg)</th><th className="p-2 text-left">F (N)</th><th className="p-2 text-left">x (cm)</th></tr></thead><tbody>{dataPoints.length === 0 ? <tr><td colSpan={4} className="p-5 text-center text-gray-400">Presiona Medir</td></tr> : dataPoints.map((point, index) => <tr key={`${point.mass}-${index}`} className="border-t"><td className="p-2">{index + 1}</td><td className="p-2 font-mono">{point.mass.toFixed(2)}</td><td className="p-2 font-mono">{point.force.toFixed(2)}</td><td className="p-2 font-mono">{(point.extension * 100).toFixed(2)}</td></tr>)}</tbody></table></div></div></section></div>}
    {phase === 'analysis' && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">🔬 Análisis</h2>{analysis ? <div className="space-y-3"><div className="grid grid-cols-2 gap-3"><div className="rounded-lg bg-blue-50 p-3 text-center"><p className="text-xs text-blue-600">k teórico</p><p className="font-mono text-xl font-bold text-blue-800">{analysis.theoreticalConstant.toFixed(2)} N/m</p></div><div className="rounded-lg bg-cyan-50 p-3 text-center"><p className="text-xs text-cyan-600">k experimental</p><p className="font-mono text-xl font-bold text-cyan-800">{analysis.experimentalConstant.toFixed(2)} N/m</p></div></div><p className="rounded-lg bg-yellow-50 p-3 text-sm">Error porcentual: <strong>{analysis.percentError.toFixed(2)}%</strong></p><p className="rounded-lg bg-gray-50 p-3 font-mono text-sm">{analysis.equation}<br />R² = {analysis.rSquared.toFixed(4)}</p></div> : <p className="py-8 text-center text-gray-500">Necesitas al menos dos mediciones.</p>}</section><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">❓ Preguntas guía</h2><ol className="list-decimal space-y-3 pl-5 text-sm text-gray-700"><li>¿La gráfica F vs x es lineal?</li><li>¿Qué representa físicamente la pendiente?</li><li>¿Qué fuentes de error pueden afectar la elongación?</li><li>¿Qué ocurriría fuera del límite elástico?</li></ol></section></div>}
    {phase === 'conclusion' && <div className="grid gap-6 lg:grid-cols-2"><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">📝 Conclusiones</h2><textarea value={conclusions} onChange={event => setConclusions(event.target.value)} rows={8} placeholder="Escribe tus conclusiones aquí..." className="w-full rounded-lg border border-gray-300 px-3 py-2 text-sm" />{hypothesis && <p className="mt-3 rounded-lg bg-blue-50 p-3 text-sm text-blue-800"><strong>Hipótesis:</strong> {hypothesis}</p>}</section><section className="rounded-xl bg-white p-5 shadow-md"><h2 className="mb-3 text-lg font-bold">📊 Resumen</h2><p className="text-sm text-gray-700">Realiza al menos cinco mediciones, compara la pendiente con k y explica las diferencias observadas.</p>{analysis && <div className="mt-4 space-y-2 text-sm"><p>k experimental: <strong>{analysis.experimentalConstant.toFixed(2)} N/m</strong></p><p>Error: <strong>{analysis.percentError.toFixed(2)}%</strong></p><p>R²: <strong>{analysis.rSquared.toFixed(4)}</strong></p></div>}</section></div>}
  </main><div className="container mx-auto px-4"><SaveExperimentButton practiceId="hooke" title="Experimento de Ley de Hooke" getPayload={() => ({ ...useLabStoreHooke.getState(), hypothesis, conclusions, analysis, savedAt: new Date().toISOString() })} /></div><footer className="border-t border-gray-200 bg-white/60 py-4 text-center text-xs text-gray-500">Laboratorio Virtual de Física General • Práctica 7: Ley de Hooke</footer></div>;
};

export default HookePractice;
